apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-pv-claim
  namespace: uptimekuma
  labels:
    app: uptimekuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi